# Generated by Django 3.0.3 on 2020-08-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200725_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=2000)),
                ('name', models.CharField(max_length=2000)),
                ('address', models.CharField(max_length=2000)),
                ('city', models.CharField(max_length=2000)),
                ('zip', models.CharField(max_length=2000)),
                ('email', models.CharField(max_length=2000)),
            ],
        ),
    ]
